on: [push, pull_request]

name: Stable

permissions:
  contents: read
  pull-requests: write

env:
  DEFAULT_OPTIONS: "--features=async,ffi,qlog"
  NO_BORING_OPTIONS: "--features=ffi,qlog --workspace --exclude h3i --exclude tokio-quiche"
  RUSTFLAGS: "-D warnings"
  RUSTTOOLCHAIN: "stable"

concurrency:
  group: ${{ github.ref }}-stable
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  network_sim:
    runs-on: ubuntu-latest
    # Only run on "pull_request" event for external PRs. This is to avoid
    # duplicate builds for PRs created from internal branches.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Create qlog dir
        run: mkdir -p qlogdir

      - name: Setup network
        run: |
          pwd
          ls scripts
          ls scripts/network_sim
          sudo ./scripts/network_sim/configure_network

      - name: Build server
        run: cargo build --bin async-http3-server

      - name: Build client
        run: cargo build --bin quiche-client

      - name: Run test
        run: |
          sudo ./scripts/network_sim/run_simulation 1000000
          sudo ./scripts/network_sim/run_simulation 10000000

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qlogdir
          path: qlogdir
